version: '3.2'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '127.0.0.1:3306:3306'
    #volumes:
    #  - ./Db/var:/var/lib/mysql

  webserver:
    build:
      context: ./webServer
    container_name: zeelo
    restart: unless-stopped
    ports:
      - "8181:80"
      - "8443:443"
    #volumes:
    #  - ${DOCUMENT_ROOT-./webServer/App}:/var/www
    links:
      - mysql
    #command: "composer install"

